로그인 기능 구현
DevKor-github/Devkor_team_D_backend pull request #3
Opened 2024-04-01 16:02 UTC by YunJaeHoon

**LoginRequestDto**
로그인 요청 dto가 구현되어 있습니다.

**LoginController.java > login 함수**
< 로그인 Controller >
LoginRequestDto를 받아서 service로 예외를 확인합니다.
(해당 이메일로 생성된 계정이 존재하는지, 비밀번호가 일치하는지 확인)
예외가 발생하지 않으면 세션을 발행합니다.

**LoginService.java > login 함수**
< 로그인 Service >
이메일이 해당하는 계정이 존재하지 않을 경우,
비밀번호가 일치하지 않을 경우에 대해서 예외를 발생시킵니다.

2024-04-01 16:04 UTC, YunJaeHoon commented
로그인 방식은 Spring Security를 통한 세션 방식으로 구현하였습니다

2024-04-02 04:47 UTC, duru100470 requested changes
👍👍

2024-04-02 04:47 UTC, duru100470 commented on src/main/java/com/example/Devkor_project/configuration/SecurityConfig.java
> +                .authorizeHttpRequests(requests -> requests
로그인 / 회원가입 경로도 외부에서 접근 가능해야 할 것 같아요

2024-04-02 04:47 UTC, duru100470 commented on src/main/java/com/example/Devkor_project/dto/LoginRequestDto.java
> +    private String email;
백엔드 측에서도 Dto 한번 Validation 해줘야 해요

2024-04-02 04:47 UTC, duru100470 commented on src/main/java/com/example/Devkor_project/service/LoginService.java
> +                .orElseThrow(() -> new AppException(ErrorCode.EMAIL_Not_Found, dto.getEmail() + "에 해당하는 계정이 존재하지 않습니다."));
로그인은 보안상의 이유로 아이디가 존재하지 않더라도 Not found 대신 비밀번호 매칭 실패와 같은 오류 코드를 보내는 것이 좋을 것 같아요

2024-04-02 04:47 UTC, duru100470 commented on src/test/java/com/example/Devkor_project/controller/LoginControllerTest.java
> +    void signUp_success()
.net 진영에선 테스트 이름을 메소드이름_테스트가실행되는시나리오_예상되는결과로 (ex. Add_SingleNumber_ReturnsSameNumber) 짓는 네이밍 컨벤션이 있는데, 저희도 이런 테케 네이밍 컨벤션을 만들까요?

2024-04-02 04:47 UTC, duru100470 commented on src/test/java/com/example/Devkor_project/controller/LoginControllerTest.java
> +        // 예상
Unit Test 본문은 Arrange, Act, Assert 크게 세부분으로 나눠서 작성하시면 후에 테스트를 볼 때 가독성이 올라가요.

https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices
단위 테스트 작성 시 유용할 정보가 많이 있으니 참고하시면 좋을 것 같습니다

2024-04-03 16:38 UTC, closed without merging