ftr: 권한 분류와 ADMIN 권한의 대학원 강의 데이터베이스 초기화 api 구현
DevKor-github/Devkor_team_D_backend pull request #8
Opened 2024-04-08 13:30 UTC by YunJaeHoon

### 권한 분류

session의 권한을 USER와 ADMIN으로 나눴습니다.
일반적으로 회원가입을 할 때는 USER 권한으로 계정이 생성됩니다.
ADMIN 계정을 만드려면 데이터베이스에 직접 sql 문을 작성해야 합니다.

---
### ADMIN 전용 API

ADMIN 계정만 요청할 수 있는 api를 만들었습니다.
해당 api 요청을 보내려면, ADMIN 권한의 세션을 획득한 후, 보내야 합니다.

**대학원 강의 데이터베이스 초기화**
**POST:"/api/admin/init-course-database"**

고려대학교 대학원 수강신청 사이트에서 대학원 강의 크롤링 데이터의 내용(data.json)을 받은뒤,
1. ADMIN 세션이 요청한 경우, 대학원 강의 데이터베이스를 해당 내용으로 초기화 후, 성공 메시지(200) 응답
2. USER 세션이 요청한 경우, 실패 메시지(401) 응답
3. 세션이 존재하지 않는 경우, 실패 메시지(401) 응답

2024-04-09 02:14 UTC, wonsang4232 commented
전체적으로 괜찮은 것 같은데, 위에 제가 쓴 코드 보시면 data.json 만들 때 Year, Term, Campus, 그리고 pColCd, pDeptCd 를 기준으로 데이터를 받아오게 되는데, 사실 데이터를 요청해보면 이 요청에 필요한 요소들이 다 데이터에 들어가있더라구요,, 

그래서 차라리 파싱 코드를 조금 변형해서, data.json 구조를 아예 1차원으로 만들어버리는 게 어떨까 싶습니다. 어차피 특정 강의 조회하게 되면 그에 해당하는 데이터들이 모조리 나오기 때문에, 현재 구조에서는 코드가 조금 비효율적으로 돌아갈 것 같아서 의견 남깁니다 !!

2024-04-09 02:31 UTC, YunJaeHoon commented
@wonsang4232 comment 감사합니다. 그런데, 제가 구현한 코드는 이미 data.json을 1차원으로 파싱한 후, 데이터베이스에 저장하는 코드입니다.
특정 강의를 조회할 때는 그냥 데이터베이스에서 조회하도록 data.json을 데이터베이스에 저장해버리는게 해당 api입니다.

![image](https://github.com/DevKor-github/academ-back/assets/104723558/982ff329-7362-4052-8225-403372512f02)

해당 이미지는 해당 api의 결과입니다. 강의 데이터 전부 문제 없이 데이터베이스에 저장해놓았습니다.

정리해서 말하자면, 해당 api는 그냥 course 데이터베이스를 초기화하는 api이기 때문에, 서비스 시작 전 딱 한번만 수행하면 다시는 수행할 일이 없는 api입니다!

2024-04-09 04:09 UTC, duru100470 requested changes
나머진 잘하신 것 같습니다

2024-04-09 04:09 UTC, duru100470 commented on src/main/java/com/example/Devkor_project/controller/AdminController.java
> +    void checkAuthority(HttpServletRequest request)
spring security에서 authentication뿐만 아니라 authority도 관리해주는 것으로 알고있는데 이런 방식으로 authority 처리해주시는 이유가 있나요?

2024-04-09 04:21 UTC, YunJaeHoon commented on src/main/java/com/example/Devkor_project/controller/AdminController.java
> +    void checkAuthority(HttpServletRequest request)
@duru100470  hasrole 같은 메서드로 세션에 권한을 부여할 수 있는 것으로 알고 있는데, 권한 정보를 다루는 부분을 인터넷에서 찾아보면서 여러 시도를 해보았지만 저에게는 쉽지 않았습니다.. spring security가 업데이트되면서 메서스 구현 방식이 계속 변하는 것 같아요.. 계속 시도하다가 결국 못해서 그냥 제가 직접 권한을 설정하고 제한을 하는게 낫다고 판단하여 이렇게 처리하였습니다. 이렇게 하는게 개인적으로는 훨씬 간단하고 직관적이라고 느껴졌습니다.

2024-04-09 04:49 UTC, merged

2024-04-10 05:24 UTC, wonsang4232 commented
@YunJaeHoon 아 제 말은 data.json으로 파일을 생성할 때 애초에 1차원으로 만들어버리자는 말이였는데 (제가 짠 코드를 변경하자는 내용이였습니다), 사실 재훈님 말대로 서비스 시작 시 1번정도만 시행되는 코드라 사실 크게 중요하진 않을 것 같습니다. 

그대로 하셔도 될 것 같습니다 !